import React,{useEffect,useMemo,useRef,useState}from"react";import{createRoot}from"react-dom/client";import{Globe2,Radio,Search,RefreshCw,ShieldCheck,MapPin,ChevronRight}from"lucide-react";import"./style.css";
import Hls from "hls.js";
function HlsVideo({src,title}:{src:string;title:string}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const v=ref.current;if(!v)return;let h:Hls|null=null;if(v.canPlayType("application/vnd.apple.mpegurl")){v.src=src}else if(Hls.isSupported()){h=new Hls({enableWorker:true});h.loadSource(src);h.attachMedia(v)}else{v.poster="";}return()=>{h?.destroy();v.removeAttribute("src");v.load()}},[src]);return <video ref={ref} title={title} controls autoPlay muted playsInline/>}
type Cam={id:number;title:string;live:boolean;player?:string;city:string;country:string;lat:number;lon:number;image?:string};type LiveSource={id:string;title:string;provider:string;player:string;city:string;country:string;lat:number;lon:number;thumbnail?:string};
function App(){const[cams,setCams]=useState<Cam[]>([]),[live,setLive]=useState<LiveSource[]>([]),[sel,setSel]=useState<Cam|null>(null),[liveSel,setLiveSel]=useState<LiveSource|null>(null),[q,setQ]=useState(""),[region,setRegion]=useState("ALL"),[liveOnly,setLiveOnly]=useState(false),[tab,setTab]=useState("map"),[favorites,setFavorites]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem("worldlive-favorites")||"[]")}catch{return[]}}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[auto,setAuto]=useState(true);
async function load(){setLoading(true);setError("");try{const r=await fetch("/api/webcams?limit=100",{cache:"no-store"}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||"Camera request failed");setCams(d.webcams||[]);setSel(x=>x&&d.webcams.some((c:Cam)=>c.id===x.id)?x:d.webcams[0]||null)}catch(e){setError(String(e))}finally{setLoading(false)}}
async function loadLive(){try{const r=await fetch("/api/live",{cache:"no-store"}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||"LIVE NOW request failed");setLive(d.sources||[]);setLiveSel(x=>x&&d.sources.some((c:LiveSource)=>c.id===x.id)?x:d.sources[0]||null)}catch(e){console.error(e)}}
useEffect(()=>{load();loadLive()},[]);useEffect(()=>{if(!auto)return;const t=setInterval(()=>{load();loadLive()},60000);return()=>clearInterval(t)},[auto]);
function nav(t:string){setTab(t);if(t==="map"){setLiveOnly(false)}if(t==="live"){setLiveOnly(true)}if(t==="discover"){setLiveOnly(false);setRegion("ALL");setQ("")}if(t==="countries"){setLiveOnly(false);setQ("")}if(t==="favorites"){setLiveOnly(false);setQ("")}}function toggleFavorite(id:number){setFavorites(x=>{const n=x.includes(id)?x.filter(v=>v!==id):[...x,id];localStorage.setItem("worldlive-favorites",JSON.stringify(n));return n})} const regions=useMemo(()=>["ALL",...Array.from(new Set(cams.map(c=>c.country).filter(Boolean))).sort()], [cams]);const shown=useMemo(()=>cams.filter(c=>(tab!=="favorites"||favorites.includes(c.id))&&(!liveOnly||c.live)&&(!q||(`${c.title} ${c.city} ${c.country}`.toLowerCase().includes(q.toLowerCase())))&&(region==="ALL"||c.country===region)),[cams,q,region,liveOnly]);
function next(){if(!sel||!shown.length)return;const i=shown.findIndex(c=>c.id===sel.id);setSel(shown[(i+1)%shown.length])}function nextLive(){if(!liveSel||!live.length)return;const i=live.findIndex(c=>c.id===liveSel.id);setLiveSel(live[(i+1)%live.length])}
return <main><header><div className="logo"><Globe2/> WORLD<span>LIVE</span></div><nav><button className={tab==="map"&&!liveOnly?"active":""} onClick={()=>nav("map")}>LIVE MAP</button><button className={tab==="live"||liveOnly?"active":""} onClick={()=>nav("live")}>LIVE NOW</button><button className={tab==="discover"?"active":""} onClick={()=>nav("discover")}>DISCOVER</button><button className={tab==="countries"?"active":""} onClick={()=>nav("countries")}>COUNTRIES</button><button className={tab==="favorites"?"active":""} onClick={()=>nav("favorites")}>FAVORITES ({favorites.length})</button></nav><div className="headright"><span><i/> NETWORK ONLINE</span><button onClick={()=>setAuto(!auto)}>{auto?"AUTO 60S":"AUTO OFF"}</button></div></header>
<section className="hero"><div className="hero-copy"><small>GLOBAL PUBLIC WEBCAMS / LIVE INTELLIGENCE</small><h1>THE WORLD<br/><em>IN VIEW.</em></h1><p>Explore verified public webcam records and genuinely available live players.</p><div className="metrics"><b>{cams.length}<small> ACTIVE SOURCES</small></b><b>{live.length}<small> LIVE NOW</small></b><b>{regions.length-1}<small> COUNTRIES</small></b></div></div><div className="orb"><Globe2/><span>WORLD<br/>LIVE</span><i className="orbit o1"/><i className="orbit o2"/></div></section>
<section className="toolbar"><div className="count">{liveOnly?`${live.length} VERIFIED LIVE FEEDS`:(loading?"CONNECTING…":error?"NETWORK ERROR":<><strong>{shown.length}</strong> cameras</>)}</div><div className="tools"><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, country or camera"/></label><select value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(r=><option key={r}>{r}</option>)}</select><button className={liveOnly?"on":""} onClick={()=>setLiveOnly(!liveOnly)}><Radio/> LIVE ONLY ({live.length})</button><button onClick={()=>{load();loadLive()}}><RefreshCw/> REFRESH</button></div></section>
{error&&<div className="error"><ShieldCheck/><div><b>Camera network unavailable</b><p>{error}</p></div></div>}
<section className="workspace"><div className="viewer"><div className="viewerhead"><span>{liveOnly?"LIVE NOW":"SELECTED FEED"}</span><small>{liveOnly?(liveSel?.country||"NO LIVE FEED"):(sel?.country||"GLOBAL")}</small></div>
{liveOnly?<>{liveSel?<><div className="player"><HlsVideo src={liveSel.player} title={liveSel.title}/><label>● LIVE NOW · {liveSel.provider}</label></div><div className="vtitle"><div><small>{liveSel.country||"GLOBAL"}</small><h2>{liveSel.title}</h2><p><MapPin/> {liveSel.city||"Unknown location"}</p></div><button onClick={nextLive}><ChevronRight/> NEXT LIVE</button></div><div className="source"><ShieldCheck/> Verified live provider · {liveSel.provider}</div></>:<div className="empty"><Radio/> {live.length===0?"No provider-supplied live players are available right now.":"Select a live feed."}</div>}</>:sel?<><div className="player">{sel.player?<iframe src={sel.player} title={sel.title} allowFullScreen/>:sel.image?<img src={sel.image}/>:<div className="empty">No current media supplied.</div>}<label className={sel.live?"":"muted"}>{sel.live?"● LIVE PLAYER":"● SOURCE VIEW"}</label></div><div className="vtitle"><div><small>{sel.country||"GLOBAL"}</small><h2>{sel.title}</h2><p><MapPin/> {sel.city||"Unknown location"}</p></div><button onClick={next}><ChevronRight/> NEXT FEED</button></div><div className="source"><ShieldCheck/> Verified provider record · Webcam ID {sel.id}</div></>:<div className="empty"><Radio/> Select a camera.</div>}</div>
<aside><div className="listhead"><span>{liveOnly?"LIVE NOW":tab==="favorites"?"FAVORITES":"CAMERAS"}</span><small>{liveOnly?live.length:shown.length} RESULTS</small></div>{liveOnly?live.map(c=><article className={liveSel?.id===c.id?"selected":""} onClick={()=>setLiveSel(c)} key={c.id}>{c.thumbnail?<img src={c.thumbnail}/>:<div className="thumb"><Globe2/></div>}<div><b>{c.title}</b><span><MapPin/> {c.city||"Unknown"}{c.country?", "+c.country:""}</span><small className="live">● LIVE NOW · {c.provider}</small></div></article>):!loading&&!error&&shown.map(c=><article className={sel?.id===c.id?"selected":""} onClick={()=>setSel(c)} key={c.id}>{c.image?<img src={c.image}/>:<div className="thumb"><Globe2/></div>}<div><b>{c.title||"Unnamed webcam"}</b><span><MapPin/> {c.city||"Unknown"}{c.country?", "+c.country:""}</span><small className={c.live?"live":"inactive"}>{c.live?"● LIVE PLAYER":"● NO LIVE PLAYER"}</small></div><button className="fav" onClick={e=>{e.stopPropagation();toggleFavorite(c.id)}}>{favorites.includes(c.id)?"★":"☆"}</button></article>)}</aside>
<div className="map"><div className="mapgrid"/><div className="maptitle"><span>{liveOnly?"LIVE NETWORK":"GLOBAL MAP"}</span><small>{liveOnly?live.length:shown.length} returned records</small></div>{(liveOnly?live:shown).map(c=><button key={c.id} className={"pin "+((liveOnly?liveSel?.id===c.id:sel?.id===c.id)?"sel ":"")+(liveOnly||c.live?"isLive":"")} style={{left:`${Math.max(1,Math.min(99,(c.lon+180)/360*100))}%`,top:`${Math.max(2,Math.min(98,(90-c.lat)/180*100))}%`}} onClick={()=>liveOnly?setLiveSel(c as LiveSource):setSel(c as Cam)} title={c.title}><i/></button>)}</div></section>
<footer>Webcams provided by Windy.com · LIVE NOW contains only provider-supplied live player embeds. No fabricated live status. Auto-refresh: {auto?"60 seconds":"off"}.</footer></main>}
createRoot(document.getElementById("root")!).render(<App/>);